version: "3"

services:
  postgres:
    container_name: test-postgres
    build:
      context: postgres/
      dockerfile: Dockerfile
      args:
        - DATASTORE_READONLY_PASSWORD=${DATASTORE_READONLY_PASSWORD}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    environment:
      - DATASTORE_READONLY_PASSWORD=${DATASTORE_READONLY_PASSWORD}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/db
    volumes:
      - test-pg_data:/var/lib/postgresql/data
    network_mode: host

  solr:
    container_name: test-solr
    image: ckan/ckan-solr:master
    network_mode: host
    volumes:
      - test-solr_data:/opt/solr/server/solr/ckan/data/index

  redis:
    container_name: test-redis
    image: redis:alpine
    network_mode: host

  datapusher:
    container_name: test-datapusher
    image: ghcr.io/keitaroinc/datapusher:${DATAPUSHER_VERSION}
    network_mode: host
    environment:
      - DATAPUSHER_MAX_CONTENT_LENGTH=${DATAPUSHER_MAX_CONTENT_LENGTH}
      - DATAPUSHER_CHUNK_SIZE=${DATAPUSHER_CHUNK_SIZE}
      - DATAPUSHER_CHUNK_INSERT_ROWS=${DATAPUSHER_CHUNK_INSERT_ROWS}
      - DATAPUSHER_DOWNLOAD_TIMEOUT=${DATAPUSHER_DOWNLOAD_TIMEOUT}
      - DATAPUSHER_SSL_VERIFY=${DATA_PUSHER_SSL_VERIFY}
      - DATAPUSHER_REWRITE_RESOURCES=${DATAPUSHER_REWRITE_RESOURCES}
      - DATAPUSHER_REWRITE_URL=${DATAPUSHER_REWRITE_URL}


volumes:
  test-pg_data: 
  test-solr_data:
