#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$PG_ROOT_USER" <<-EOSQL
    CREATE ROLE "$CKAN_DB_USER" NOSUPERUSER CREATEDB CREATEROLE LOGIN PASSWORD '$CKAN_DB_PASS';
    CREATE DATABASE "$CKAN_DB_NAME" OWNER "$CKAN_DB_USER" ENCODING 'utf-8';
EOSQL