#!/bin/bash
set -e

if [ "${CKAN_DATASTORE_DB_USER}" = "${CKAN_DB_USER}" ]; then
# Only create the database, as the user is already created.
psql -v ON_ERROR_STOP=1 --username "$PG_ROOT_USER" <<-EOSQL
    CREATE DATABASE "$CKAN_DATASTORE_DB_NAME" OWNER "$CKAN_DB_USER" ENCODING 'utf-8';
EOSQL
else
psql -v ON_ERROR_STOP=1 --username "$PG_ROOT_USER" <<-EOSQL
    CREATE ROLE "$CKAN_DATASTORE_DB_USER" NOSUPERUSER NOCREATEDB NOCREATEROLE LOGIN PASSWORD '$CKAN_DATASTORE_DB_PASS';
    CREATE DATABASE "$CKAN_DATASTORE_DB_NAME" OWNER "$CKAN_DB_USER" ENCODING 'utf-8';
EOSQL
fi