version: "3"

services:
  postgres:
    container_name: test_2.7-postgres
    build:
      context: postgres/
      dockerfile: Dockerfile
      args:
        - DATASTORE_READONLY_PASSWORD=${DATASTORE_READONLY_PASSWORD}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    environment:
      - DATASTORE_READONLY_PASSWORD=${DATASTORE_READONLY_PASSWORD}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/db
    volumes:
      - test_2.7-pg_data:/var/lib/postgresql/data
    network_mode: host

  solr:
    container_name: test_2.7-solr
    build:
      context: solr/
    ports:
      - "8983:8983"
    volumes:
      - test_2.7-solr_data:/opt/solr/server/solr/ckan/data/index

  redis:
    container_name: test_2.7-redis
    image: redis:alpine
    network_mode: host


volumes:
  test_2.7-pg_data: 
  test_2.7-solr_data:
